import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { Geist, Geist_Mono,Space_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import ScrollExperience from "@/components/layout/ScrollExperience";
import { routing } from "@/i18n/routing";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const spaceGrotest = Space_Grotesk({
  variable:"--font-space-grotesk",
  weight:["300","400","500","600","700"],
  subsets:['latin']
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: LayoutProps<"/[local]">) {
  const { local } = await params;
  if (!hasLocale(routing.locales, local)) notFound();

  await setRequestLocale(local);
  const messages = await getMessages();

  return (
    <html
      lang={local}
      dir={local === 'ar' ? 'rtl' : 'ltr'}
      className={`${geistSans.variable} ${geistMono.variable} ${spaceGrotest.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NextIntlClientProvider messages={messages}>
          <Navbar />
          {children}
          <Footer />
          <ScrollExperience locale={local} />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
